package com.zelgius.controller.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006784)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFbae9ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f2a)
val md_theme_light_secondary = Color(0xFF745c00)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffe079)
val md_theme_light_onSecondaryContainer = Color(0xFF231b00)
val md_theme_light_tertiary = Color(0xFF006685)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbce9ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001f2a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdce4e9)
val md_theme_light_onSurfaceVariant = Color(0xFF40484c)
val md_theme_light_outline = Color(0xFF70787d)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)

val md_theme_dark_primary = Color(0xFF61d3ff)
val md_theme_dark_onPrimary = Color(0xFF003546)
val md_theme_dark_primaryContainer = Color(0xFF004d64)
val md_theme_dark_onPrimaryContainer = Color(0xFFbae9ff)
val md_theme_dark_secondary = Color(0xFFe8c349)
val md_theme_dark_onSecondary = Color(0xFF3d2f00)
val md_theme_dark_secondaryContainer = Color(0xFF574400)
val md_theme_dark_onSecondaryContainer = Color(0xFFffe079)
val md_theme_dark_tertiary = Color(0xFF65d3ff)
val md_theme_dark_onTertiary = Color(0xFF003547)
val md_theme_dark_tertiaryContainer = Color(0xFF004d66)
val md_theme_dark_onTertiaryContainer = Color(0xFFbce9ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF40484c)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c8cd)
val md_theme_dark_outline = Color(0xFF8a9296)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFF455a64)
val errorColor = Color(0xFFba1b1b)
val warningColor = Color(0xFFFFC107)
val okColor = Color(0xFF4CAF50)

val xButtonColor = Color(0xFF42a5f4)
val yButtonColor = Color(0xFF43a047)
val bButtonColor = Color(0xFFf57f17)
val aButtonColor = Color(0xFFff1744)
